LaughSeenShpi/Controllers/CreateRoomController.cs
using LaughSeenShpi.DataAccess.Data;
using LaughSeenShpi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LaughSeenShpi.Controllers
{
    public class CreateRoomController : Controller
    {

        private readonly ApplicationDbContext _db;
        private DbSet<Room> dbSet;
        public CreateRoomController(ApplicationDbContext db)
        {
            _db = db;
            this.dbSet = db.Set<Room>();
        }




        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Post(Room room)
        {

            Room existingRoom;

            existingRoom = _db.Room.Where(s => s.Name == room.Name).FirstOrDefault();



            if (existingRoom == null)
            {


                dbSet.Add(room);

                _db.SaveChanges();
            }
            //return View("Room/Index",room);



            return RedirectToAction("Index", "PickTheUserName", existingRoom==null ?  room:existingRoom);
        
        }





     
    }
}

LaughSeenShpi/Controllers/HomeController.cs
using LaughSeenShpi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LaughSeenShpi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LaughSeenShpi/Controllers/ReadWriteMessagesController.cs
using LaughSeenShpi.DataAccess.Data;
using LaughSeenShpi.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using PusherServer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LaughSeenShpi.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class ReadWriteMessagesController : ControllerBase
    {

        private readonly ApplicationDbContext _db;
        private readonly DbSet<Messages> dbSet;

        public ReadWriteMessagesController(ApplicationDbContext db)
        {
            _db = db;
            dbSet = _db.Set<Messages>();
        }




        
         
         [HttpGet("{RoomId}")]
         
          public IEnumerable<Messages> GetMessages(int RoomId)
        {

            var messages = _db.Room.Where(s => s.ID == RoomId)
            .Join(_db.RoomMembers, r => r.ID, rm => rm.MemberRoomId, (r, rm) => rm)
            .Join(_db.Messages, rm => rm.MemberID, m => m.RoomMemberId, (rm, m) => m).Include(rm=>rm.RoomMembers).ThenInclude(rm=>rm.Room)
            .ToList().OrderBy(m=>m.SendTime);

            return messages;

        }

        public async Task<IActionResult> AddMessages(Messages message)
        {

            if (message.Content!="")
            {

                message.SeenTime = DateTime.Now;
                message.SendTime = DateTime.Now; //this needs to be changed in order to have the logic when the message is seen





                _db.Messages.Add(message);

                _db.SaveChanges();

                var messagesPlusSender = _db.Messages.Where(m => m.ID == message.ID).Include(m => m.RoomMembers).Where(m => m.RoomMembers.MemberID == message.RoomMemberId).FirstOrDefault();

                var room = _db.RoomMembers.Where(s => s.MemberID == message.RoomMemberId)
      .Join(_db.Room, rm => rm.MemberRoomId, r => r.ID, (rm, r) => r).FirstOrDefault();

                MessagePlusRoom messagePlusRoom = new MessagePlusRoom { room = room, messages = messagesPlusSender };



                var options = new PusherOptions
                {
                    Cluster = "eu",
                    Encrypted = true
                };
                var pusher = new Pusher(
                    "1126876",
                    "07088996639e59625df1",
                    "588dfb9942c061b04ff6",
                    options
                );

                var result = await pusher.TriggerAsync(
                     room.ID.ToString(),
                     "new_message",
                     new { messagePlusRoom },
                     new TriggerOptions() { SocketId = message.socketId });


                return new ObjectResult(new { status = "success", data = message });
            }
            return new ObjectResult(new { status = "erroo"});

        }


        public async  void UpdateRoom(RoomMembers roomMember)
        {
            var roomFromDb = _db.Room.Where(r=>r.ID== roomMember.Room.ID).FirstOrDefault();

            roomFromDb.CurrentTime = roomMember.Room.CurrentTime;
            roomFromDb.PlayTheMovie = roomMember.Room.PlayTheMovie;

            _db.SaveChanges();

            var options = new PusherOptions
            {
                Cluster = "eu",
                Encrypted = true
            };
            var pusher = new Pusher(
                "1126876",
                "07088996639e59625df1",
                "588dfb9942c061b04ff6",
                options
            );

            var result = await pusher.TriggerAsync(
                 roomMember.Room.ID.ToString(),
                 "video_parameters_changed",
                 new { roomMember },
                 new TriggerOptions() {  });

        }






    }


    public class MessagePlusRoom
    {

        public Room room { get; set; }

        public Messages messages { get; set; }

    }

}

LaughSeenShpi/Controllers/RoomController.cs
using LaughSeenShpi.DataAccess.Data;
using LaughSeenShpi.Models;
using LaughSeenShpi.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LaughSeenShpi.Controllers
{
    public class RoomController : Controller
    {
        private readonly ApplicationDbContext _db;


        public RoomController(ApplicationDbContext db)
        {
            _db = db;

        }



        public IActionResult Index(RoomMembers roomMembersWithRoomData)
        {
            //ViewBag.messages = JsonConvert.DeserializeObject<IEnumerable<Messages>>( TempData["messages"].ToString());
           //ViewBag.Room= JsonConvert.DeserializeObject<Room>(TempData["Room"].ToString());

            RoomMembers roomMembersAndRoom = _db.RoomMembers.Where(rm => rm.MemberID == roomMembersWithRoomData.MemberID).Include(rm => rm.Room).FirstOrDefault();

            //need to delete this and uncomment the first above line
            //ViewBag.Room = new Room();


            return View(roomMembersAndRoom);
        }
    }
}

LaughSeenShpi/Views/CreateRoom/Index.cshtml
 @model LaughSeenShpi.Models.Room


<div class="row vh-100 "  >
<div class="col-sm-12 my-auto">
<form method="post" >
    <fieldset>

        <div class="form-group col-sm-9 float-left">
            <div class="col-sm-12">
                <label for="exampleInputEmail1" class="form-text" style="font-size:25px">Room Name</label>
            </div>
            <div class="col-sm-12 float-left">
                <input type="text" class="form-control" asp-for="@Model.Name" id="exampleInputEmail1" required aria-describedby="emailHelp" placeholder="Enter room name">
                <small id="emailHelp" class="form-text text-muted">Enjoy chatting with your friends and your loving ones</small>
            </div>

            <div class="col-sm-12">
                <label for="exampleInputEmail1" class="form-text" style="font-size:25px">Movie URL</label>
            </div>
            <div class="col-sm-9 float-left">
                <input type="text" class="form-control" asp-for="@Model.MovieUrl" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter moive URL">
                @*<small id="emailHelp" class="form-text text-muted">Enjoy chatting with your friends and your loving ones</small>*@
            </div>

            <div class="col-sm-3 float-left">
                <button type="submit" asp-controller="CreateRoom" asp-action="Post" class="btn btn-primary col-sm-12">Submit room name</button>
            </div>

        </div>

    </fieldset>
</form>
        </div>
</div>

LaughSeenShpi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LaughSeenShpi/Views/PickTheUserName/Index.cshtml
@model LaughSeenShpi.Models.RoomMembers


<div class="row vh-100 ">
    <div class="col-sm-12 my-auto">
        <form method="post">
            <fieldset>

                <div class="form-group col-sm-9 float-left">
                    <div class="col-sm-12">
                        <label for="exampleInputEmail1" class="form-text" style="font-size:25px">You have joined @ViewBag.Room.Name Please pick a username </label>
                    </div>
                    <div class="col-sm-9 float-left">
                        <input type="text" class="form-control" asp-for="@Model.MemberName" id="exampleInputEmail1" aria-describedby="emailHelp" required placeholder="Enter your user name here">
                        <small id="emailHelp" class="form-text text-muted">Enjoy chatting with your friends and your loving ones</small>
                        <input type="hidden" class="form-control" asp-for="@Model.MemberRoomId"  value="@ViewBag.Room.ID" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter your user name here">
                    </div>

                    <div class="col-sm-3 float-left">
                        <button type="submit" asp-controller="PickTheUserName" asp-action="Post" class="btn btn-primary col-sm-12">Submit username</button>
                    </div>

                </div>

            </fieldset>
        </form>
    </div>
</div>

LaughSeenShpi/Views/Room/Index.cshtml
@model LaughSeenShpi.Models.RoomMembers

@{ 

    Layout = "~/Views/Shared/_Layout - Copy.cshtml";
}




            <div class="container" style="padding:0;margin:0;">
                @*<h3 class=" text-center">@ViewBag.Room.Name      </h3>*@
                <div class="messaging" style="padding:0;margin:0;">








                                        <div class="inbox_msg" style="padding:0;margin:0;height:100vh">

                                            <div class="mesgs col-sm-10" style=" float:left; padding-left:0; padding-right:0;  height:100vh;background-color:black;" id="movie">


                                                    @*<IFRAME SRC="" class="col-sm-12 h-100" style="margin-left:0;margin-right:0"  FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO  allowfullscreen>
                                                    </IFRAME>*@

                                                <video id="movieVideo" muted="muted"  src="@Model.Room.MovieUrl" class="col-sm-12 h-100" style="margin-left:0;margin-right:0; height:100vh;" controls> </video>

                                            </div>



                                            <div class="mesgs col-sm-2" style="float:right;padding:0;margin:0;">
                                                <div class="col-sm-12 text-white font-italic" style="height:5vh;"> <h3 class=" text-center">@Model.Room.Name      </h3>  </div>
                                                <div class="msg_history" id="messageHistoryDiv" style="padding:0;margin:0;">

                           


                                                    @*<div class="col-sm-12 text-white-50 text-sm-center">
                                                        <span><i>Someone paused the video</i> </span>


                                                    </div>*@

                              
                                                    @*<div class="outgoing_msg">
                                   
                                                        <div class="sent_msg">
                                                            <p style="margin-bottom:0">Test1</p>
                                                            <span class="time_date" style="padding-top:0">Test 1</span>
                                                        </div>
                                                    </div>

                                   
                
                                                            <div class="incoming_msg">
                                                                <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                                                                <div class="received_msg">
                                                                    <span class="small"  style="padding-top:0"> Username </span>
                                                                    <div class="received_withd_msg" style="word-wrap:break-word">
                                                                        <p style="margin-bottom:0">Test 1</p>
                                                                        <span class="time_date" style="padding-top:0"> Test 1 </span>
                                                                    </div>
                                                                </div>
                                                            </div>*@

                                        
                                 

                                                </div>
                                                <div class="type_msg">
                                                    <div class="input_msg_write">
                                                        <input type="text" class="write_msg text-white" id="MessageContent" required placeholder="Type a message" />
                                                        <input type="hidden" class="write_msg text-white" id="MessageRoomMemberId" value="@Model.MemberID" placeholder="Type a message" />
                                                        <input type="hidden" class="write_msg text-white" id="MessageRoomMemberName" value="@Model.MemberName" placeholder="Type a message" />
                                                        <input type="hidden" class="write_msg" id="RoomId" value="@Model.Room.ID" placeholder="Type a message" />
                                                        <button type="button" asp-action="Index" id="SendMessageButton" class="msg_send_btn"> <i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                </div>





            </div>

LaughSeenShpi/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaughSeenShpi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet" />


</head>
<body style="margin:0;">

    <div class="col-sm-12 h-100" style="margin:0;background-color:black">
               @RenderBody()

    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://js.pusher.com/7.0/pusher.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

LaughSeenShpi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaughSeenShpi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="CreateRoom" asp-action="Index">LaughSeenShpi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - LaughSeenShpi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://js.pusher.com/7.0/pusher.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>